type = "about"
title = "About"

[profile]
research_interests = [
  "AI for Healthcare",
  "Smart Sensing",
  "Mobile Sensing"
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"

[[sections]]
id = "appointment_education"
type = "markdown"
source = "appointment_education.md"
title = "🎓 Education"

[[sections]]
id = "selected_honors"
type = "markdown"
source = "selected_honors.md"
title = "🏅 Selected Honors"

[[sections]]
id = "featured_publications"
type = "publications"
title = "Selected Publications"
filter = "selected"
limit = 5

[[sections]]
id = "news"
type = "list"
title = "News"
source = "news.toml"

[[sections]]
id = "global_visitors_map"
type = "visitors_map"
title = "Global Visitors Map"
script_src = "https://mapmyvisitors.com/map.js?d=JKEGA69pqRXbCgVZkoEtHWmT3HpsclcvBnnmlJAR7YM&cl=ffffff&w=a"
image_href = "https://mapmyvisitors.com/web/1c669"
image_src = "https://mapmyvisitors.com/map.png?d=JKEGA69pqRXbCgVZkoEtHWmT3HpsclcvBnnmlJAR7YM&cl=ffffff"
