[site]
title = "Yizhen Zhang"
description = "Ph.D. student in Computer Science and Engineering at HKUST."
favicon = "/graduate-hat.png"
last_updated = "July 2, 2026"

[author]
name = "Yizhen Zhang"
title = "Ph.D. Student"
institution = "HKUST CSE"
avatar = "/bio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "yzhangtf@connect.ust.hk"
location = "Hong Kong SAR"
location_url = "https://maps.google.com/?q=Hong+Kong+University+of+Science+and+Technology"
location_details = [
  "Department of Computer Science and Engineering,",
  "Hong Kong University of Science and Technology"
]
google_scholar = "https://scholar.google.com/citations?user=ZA3B-qcAAAAJ&hl=en&inst=1381320739207392350"
orcid = "https://orcid.org/0009-0005-7530-9621"
github = "https://github.com/yizhencse"
linkedin = ""

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
