type = "card"
title = "Teaching"
description = "Courses I have assisted with as a teaching assistant."

[[items]]
title = "COMP 2012: Object-Oriented Programming and Data Structures"
subtitle = "Teaching Assistant"
date = "Spring 2025"
content = "Hong Kong University of Science and Technology."
tags = ["Undergraduate", "Computer Science", "Teaching Assistant"]

[[items]]
title = "COMP 2011: Programming with C++"
subtitle = "Teaching Assistant"
date = "Fall 2025"
content = "Hong Kong University of Science and Technology."
tags = ["Undergraduate", "Computer Science", "Teaching Assistant"]
